version: '2.0'
services:
  service:
    container_name: iservice
    build:
      context: service
      dockerfile: Dockerfile
    image: iservice:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5434:5432'
    restart: always